Graphic link feature
adaptlearning/adapt-contrib-graphic pull request #81
Opened 2021-08-04 13:03 UTC by guywillis

Resolves https://github.com/adaptlearning/adapt_framework/issues/2832

* Allows the graphic to be a clickable link 
* Link can be an Adapt id reference (#/id/c-10), external url (https://www.adaptlearning.org/), or relative file (course/en/images/vanilla-swatch.jpg)

2021-09-06 09:42 UTC, oliverfoster commented
@guywillis this is now a jsx component, so you may have to start again?

2021-09-20 09:02 UTC, oliverfoster commented
@guywillis yeet

2021-10-20 05:14 UTC, oliverfoster requested changes

2021-10-20 05:14 UTC, oliverfoster commented on README.md
> +>**\_target** (string): The target attribute specifies where to open the link or linked document. Acceptable values are `_blank` (opens the linked document in a new window or tab), `_parent` (opens t
brackets aren't needed.

2021-10-20 05:14 UTC, oliverfoster commented on js/GraphicView.js
> +    const target = item._target || '_blank';
```suggestion
    const { _url: url, _target: target = '_blank' } = item;
```

2021-10-20 05:14 UTC, oliverfoster commented on js/GraphicView.js
> +  }
```suggestion
    const isNewWindow = (target !== '_self');
    if (isNewWindow) return window.open(url, target);
    const isRouterNavigation = (url.substr(0, 1) === '#');
    if (isRouterNavigation) return Backbone.history.navigate(url, { trigger: true });
    window.location.href = url;
  }
```

2021-11-01 15:48 UTC, kirsty-hames approved these changes

2021-11-01 15:51 UTC, merged